name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main
        with:
          power: true

      - name: Check formatting
        run: make code-check || echo "Run `make pre-ci`"

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/sbt-vcpkg/vcpkg-install
            ~/.cache/sbt-vcpkg/vcpkg-install
            ~/.cache/sbt-vcpkg/vcpkg
          key: ${{ runner.os }}-sbt-vcpkg

      - name: Test 
        run: |
          docker run -d -p 8081:80 kennethreitz/httpbin
          HTTPBIN_URL=http://localhost:8081 make tests

      - name: Check documentation compiles and runs
        run: make check-docs && make run-example

      - name: Publish snapshot 
        if: github.ref == 'refs/heads/main'
        run: make publish-snapshot
        env:
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

      - name: Publish 
        if: startsWith(github.ref, 'refs/tags/v') 
        run: make publish
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

